# Site settings
title: Keinu
email: site@keinu.net
description: > # this means to ignore newlines until "baseurl:"
  thoughts, experience, perception
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.keinu.net" # the base hostname & protocol for your site

twitter_username: xabs
github_username: keinu

# Build settings
markdown: kramdown

sass:
  style: compressed